EsseyRoyal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.sitemaps.views import sitemap
from django.shortcuts import redirect
from django.urls import path, include

from appaaa.cron import search_deadline, check_order
from appaaa.sitemaps import ArticleSitemap, StaticViewSitemap
from appaaa.views import HomePageViews, feedback, calculate_home, order_feedback, add_testimonial, add_word
from apporders.ajax import chat_message_accept
from appusers.models import User
from appusers.views import register, login_user

sitemaps = {
    'articles': ArticleSitemap,
    'static': StaticViewSitemap
}


def redirect_dashboard(request):
    if request.user.is_authenticated:
        user = User.objects.get(email=request.user)
        group = [g for g in user.groups.all()]
        print(group)
        if len(group) != 0:
            group_name = group[0].name
            if group_name == 'Customer':
                return redirect('/c/orders/')
            if group_name == 'Writer':
                return redirect('/w/orders/')
            if group_name == 'Manager':
                return redirect('/m/orders/')
        else:
            return redirect('/a/')
    else:
        return redirect('/')


admin.site.site_header = 'Панель управления'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', HomePageViews.as_view(), name='home'),
    path('cron/search-deadline/', search_deadline),
    path('cron/check-orders/', check_order),
    path('accounts/login/', login_user, name='login'),
    path('add-comment/', add_testimonial, name='add-comment'),
    path('feedback/', feedback, name='feedback'),
    path('accounts/register/', register, name='register'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('rct/', redirect_dashboard),

    path('ajax/chat-message-accept/', chat_message_accept),
    path('ajax/calculate/', calculate_home),
    path('ajax/order-feedback/', order_feedback),
    path('ajax/add-word/', add_word),
    path('blog/', include('appblog.urls', namespace='appblog')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('c/', include('appdashboard.c', namespace='customer')),
    path('w/', include('appdashboard.w', namespace='writer')),
    path('m/', include('appdashboard.m', namespace='manager')),
    path('a/', include('appdashboard.a', namespace='administrator')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from appblog.views import ListArticles, article, article_edit, article_remove

app_name = 'appblog'
urlpatterns = [
    path('', ListArticles.as_view(), name='main'),
    path('article/<int:pk>/edit/', article_edit, name='article-edit'),
    path('article/<int:pk>/remove/', article_remove, name='article-remove'),
    path('article/<int:pk>/', article, name='article'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apporders/forms.py
import datetime

from ckeditor.widgets import CKEditorWidget
from django import forms

from apporders.models import FormatOrder, TypeOrder, Order, PriceDeadline


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['title', 'format_order', 'description']
        widgets = {
            'format_order': forms.Select(attrs={'class': 'browser-default custom-select'}),
            'description': CKEditorWidget(),
        }


class OrderAddForm(forms.Form):
    BIRTH_YEAR_CHOICES = ['1980', '1981', '1982']
    title = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Type a title...'}))
    type_order = forms.ModelChoiceField(queryset=TypeOrder.objects.all(), required=True, label='Type of order',
                                        widget=forms.Select(attrs={'class': 'browser-default custom-select'}))
    format_order = forms.ModelChoiceField(queryset=FormatOrder.objects.all(), required=True, label='Citation formatting',
                                          widget=forms.Select(attrs={'class': 'browser-default custom-select'}))
    # number_page = forms.IntegerField(required=True, label='Number of pages', widget=forms.NumberInput(
    #     attrs={
    #         'placeholder': 'Choose a number',
    #         'class': 'browser-default custom-select',
    #     }
    # ))
    _date = datetime.date.today() + datetime.timedelta(days=8)
    date_deadline = forms.DateField(
        required=True, input_formats=['%d-%m-%Y'], label='Deadline',
        widget=forms.DateInput(
            attrs={
                'type': 'text',
                'class': 'browser-default custom-select',
                'id': 'date_deadline',
                'placeholder': 'Choose date',
                'autocomplete': 'off'
            }
        )
    )
    time_deadline = forms.TimeField(
        required=True, label='Deadline Time',
        widget=forms.TimeInput(
            attrs={
                'type': 'text',
                'class': 'browser-default custom-select',
                'id': 'time_deadline',
                'placeholder': 'Choose time',
                'autocomplete': 'off'
            }
        )
    )
    number_page = forms.CharField(required=True, label='Number of pages', widget=forms.Select(
        attrs={
            'class': 'browser-default custom-select',
            'placeholder': 'Choose a number'
        }
    ))
    # deadline_writer = forms.DateTimeField()
    # attached_files = forms.FileField(label='Files', widget=forms.ClearableFileInput(attrs={'multiple': True}))
    description = forms.CharField(widget=CKEditorWidget(attrs={'placeholder': 'Describe your order in more detail...'}), required=False)

# class OrderForm(forms.ModelForm):
# deadline_writer = forms.DateTimeField(
#     required=False, input_formats=['%Y-%m-%dT%H:%M:%S+0000'],
#     widget=forms.DateTimeInput(
#         attrs={
#             'type': 'datetime-local',
#             'class': 'browser-default custom-select'
#         })
# )

# class Meta:
#     model = Order
#     exclude = ['customer', 'created_datetime', 'status']
#     widgets = {
#         'format_order': forms.Select(attrs={'class': 'browser-default custom-select'}),
#         'deadline': forms.Select(attrs={'class': 'browser-default custom-select'}),
#         'attached_files': forms.ClearableFileInput(attrs={'multiple': True}),
#         'feedback': CKEditorWidget(),
#         'deadline_writer': forms.DateTimeInput(
#             attrs={
#                 'class': 'browser-default custom-select'
#             }
#         )
#     }


class TypeOrderForm(forms.ModelForm):
    class Meta:
        model = TypeOrder
        fields = '__all__'


class FormatOrderForm(forms.ModelForm):
    class Meta:
        model = FormatOrder
        fields = '__all__'


class PriceDeadlineForm(forms.ModelForm):
    class Meta:
        model = PriceDeadline
        fields = '__all__'

templates/dashboard-v2/c/orders/completed.html
<table class="table">
    <thead>
    <tr>
        <th scope="col">Title</th>
        <th scope="col">Per page</th>
        <th scope="col">Pages</th>
        <th scope="col">Total cost</th>
        <th scope="col">Expiry date</th>
    </tr>
    </thead>
    <tbody>
    {% for order in completed %}
        <tr>
            <td>
                <a href="{% url 'customer:order-completed' order.id %}" class="text-primary">
                    {{ order.title }}
                </a>
            </td>
            <td>${{ order.per_page|floatformat }}</td>
            <td>{{ order.number_page }}</td>
            <td>${{ order.total_cost|floatformat }}</td>
            <td>{{ order.completed_datetime|date:"H:m d M" }}</td>
        </tr>
    {% endfor %}

    </tbody>
</table>

templates/dashboard-v2/c/orders/in-process.html
<table class="table">
    <thead>
    <tr>
        <th scope="col">Title</th>
        <th scope="col">Per page</th>
        <th scope="col">Pages</th>
        <th scope="col">Total cost</th>
        <th scope="col">Date of adoption</th>
    </tr>
    </thead>
    <tbody>
    {% for order in in_process %}
        <tr>
            <td>
                <a href="{% url 'customer:order-inprocess' order.id %}" class="text-primary">
                    {{ order.title }}
                </a>
            </td>
            <td>${{ order.per_page|floatformat }}</td>
            <td>{{ order.number_page }}</td>
            <td>${{ order.total_cost|floatformat }}</td>
            <td>{{ order.additionallyorder.created_datetime|date:"H:m d M" }}</td>
        </tr>
    {% endfor %}

    </tbody>
</table>

templates/dashboard-v2/c/orders/in-review.html
<table class="table">
    <thead>
    <tr>
        <th scope="col">Title</th>
        <th scope="col" class="d-none d-sm-table-cell">Pages</th>
        <th scope="col">Total cost</th>
        <th scope="col">Deadline</th>
    </tr>
    </thead>
    <tbody>
    {% for order in in_review %}
        <tr>
            <td>
                <a href="{% url 'customer:order-preview' order.id %}" class="text-primary">
                    {{ order.title }}
                </a>
            </td>
            <td class="d-none d-sm-table-cell">{{ order.number_page }}</td>
            <td>${{ order.total_cost|floatformat }}</td>
            <td>{{ order.deadline|date:"H:m d M" }}</td>
        </tr>
    {% endfor %}

    </tbody>
</table>

templates/dashboard-v2/c/orders/new-order.html
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    <table class="table">
        {% for field in new_order %}
            {% if forloop.last %}
                <tr class="tr-last">
                    <td width="150">{{ field.label }}</td>
                    <td>{{ field }}</td>
                </tr>
                {% if field.errors %}
                    <tr>
                        <td></td>
                        <td>{{ field.errors }}</td>
                    </tr>
                {% endif %}
            {% else %}
                <tr>
                    <td width="150">{{ field.label }}</td>
                    <td>{{ field }}</td>
                </tr>
                {% if field.errors %}
                    <tr>
                        <td></td>
                        <td>{{ field.errors }}</td>
                    </tr>
                {% endif %}
            {% endif %}
        {% endfor %}
        <tr>
            <td><label for="id_attached-files">Attached files</label></td>
            <td>
                <input type="file" name="attached-files" id="id_attached-files" multiple>
                <small>.xls .docx .pdf .xlsx</small>
            </td>
        </tr>
    </table>
    <button type="submit" class="btn bg-btn">Send</button>
</form>

templates/dashboard-v2/c/orders/tabs.html
{% extends 'dashboard-v2/c/index.html' %}

{% block css-down %}
    <style>
        ::-webkit-input-placeholder {color:#999; opacity:1; font-weight: 300}/* webkit */
        ::-moz-placeholder          {color:#999; opacity:1; font-weight: 300}/* Firefox 19+ */
        :-moz-placeholder           {color:#999; opacity:1; font-weight: 300}/* Firefox 18- */
        :-ms-input-placeholder      {color:#999; opacity:1; font-weight: 300}/* IE */
        .custom-select {
            height: calc(1.25rem + 2px);
            padding: .75rem 1.75rem .75rem .35rem;
            border: 1px solid #a9a9a9;
            border-radius: 0;
        }
        .select2-container--default .select2-selection--single {
            border: 1px solid #a9a9a9;
            border-radius: 0;
        }
    </style>
{% endblock %}

{% block title %}
    Dashboard - Orders
{% endblock %}

{% block section %}

    <div class="classic-tabs">

        <ul class="nav tabs-orange justify-content-around" id="myClassicTabOrange" role="tablist">
            <li class="nav-item" style="margin-left: 0;">
                <a class="nav-link waves-light active show" id="profile-tab-classic-orange" data-toggle="tab"
                   href="#profile-classic-orange"
                   role="tab" aria-controls="profile-classic-orange" aria-selected="true"><i
                        class="fas fa-search fa-2x pb-2"
                        aria-hidden="true"></i><br>Pending</a>
            </li>
            <li class="nav-item">
                <a class="nav-link waves-light" id="follow-tab-classic-orange" data-toggle="tab"
                   href="#follow-classic-orange"
                   role="tab" aria-controls="follow-classic-orange" aria-selected="false"><i
                        class="fas fa-spinner fa-2x pb-2"
                        aria-hidden="true"></i><br>In process</a>
            </li>
            <li class="nav-item">
                <a class="nav-link waves-light" id="contact-tab-classic-orange" data-toggle="tab"
                   href="#contact-classic-orange"
                   role="tab" aria-controls="contact-classic-orange" aria-selected="false"><i
                        class="fas fa-check fa-2x pb-2"
                        aria-hidden="true"></i><br>Completed</a>
            </li>
            <li class="nav-item">
                <a class="nav-link waves-light" id="awesome-tab-classic-orange" data-toggle="tab"
                   href="#awesome-classic-orange"
                   role="tab" aria-controls="awesome-classic-orange" aria-selected="false"><i
                        class="fas fa-plus fa-2x pb-2"
                        aria-hidden="true"></i><br>New order</a>
            </li>
        </ul>

        <div class="tab-content" id="myClassicTabContentOrange">
            <div class="tab-pane fade active show" id="profile-classic-orange" role="tabpanel"
                 aria-labelledby="profile-tab-classic-orange">
                {% include 'dashboard-v2/c/orders/in-review.html' %}
            </div>
            <div class="tab-pane fade" id="follow-classic-orange" role="tabpanel"
                 aria-labelledby="follow-tab-classic-orange">
                {% include 'dashboard-v2/c/orders/in-process.html' %}
            </div>
            <div class="tab-pane fade" id="contact-classic-orange" role="tabpanel"
                 aria-labelledby="contact-tab-classic-orange">
                {% include 'dashboard-v2/c/orders/completed.html' %}
            </div>
            <div class="tab-pane fade" id="awesome-classic-orange" role="tabpanel"
                 aria-labelledby="awesome-tab-classic-orange">
                {% include 'dashboard-v2/c/orders/new-order.html' %}
            </div>
        </div>

    </div>

{% endblock %}

{% block scripts %}
    <script>
        // Вставляем дефолтные данные для даты и времени
        $('#date_deadline').datetimepicker({
            format: 'd-m-Y',
            {#value: new Date(new Date().setDate(new Date().getDate() + 2)),#}
            timepicker: false
        });
        $('#time_deadline').datetimepicker({
            format: "H:i",
            {#value: "00:00",#}
            datepicker: false
        });

        $('#id_type_order').select2({
            width: '100%',
            placeholder: 'Choose a type'
        });
        $('#id_format_order').select2({
            width: '100%',
            placeholder: 'Choose a citation formatiing'
        });

        let choices = [];
        for (let i = 0; i < 50; i++) {
            choices.push({id: i+1, text: `${i+1}`})
        }
        $('#id_number_page').select2({
            width: '75px',
            placeholder: 'Choose a number',
            data: choices,
        });

        // CUSTOMER CALCULATE
        function fnCalculate(data) {
            $('.new-tr').remove();
            $('.tr-last').before(
                `
                <tr class="new-tr">
                    <td>Calculation: </td>
                    <td style="color: #215da3; text-align: center;">
                        <div style="display: inline-block; padding-right: 75px; text-align: center;">Per page<br><strong>$${data.per_page}</strong></div>
                        <div style="display: inline-block; text-align: center;">Total cost<br><strong>$${data.total_cost}</strong></div></td>
                </tr>
                `
            );
        }

        function fnCount() {
            let typeOrder = $('#id_type_order').val(); // 4
            let pagesOrder = $('#id_number_page').val(); // 4
            let date = $('#date_deadline').val(); // 30-05-2019
            let time = $('#time_deadline').val(); // 17:30
            let dataObj = {
                typeOrder: typeOrder,
                pagesOrder: pagesOrder,
                date: date,
                time: time
            };
            ajaxQyery('calculate', dataObj, fnCalculate);
        }

        let listChangeCalculate = ['#id_type_order', '#id_number_page', '#date_deadline', '#time_deadline'];

        for (let i = 0; i < listChangeCalculate.length; i++) {
            $(listChangeCalculate[i]).change(function () {
                fnCount();
            })
        }
    </script>
{% endblock %}