EsseyRoyal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.sitemaps.views import sitemap
from django.shortcuts import redirect
from django.urls import path, include

from appaaa.cron import search_deadline, check_order
from appaaa.sitemaps import ArticleSitemap, StaticViewSitemap
from appaaa.views import HomePageViews, feedback, calculate_home, order_feedback, add_testimonial, add_word
from apporders.ajax import chat_message_accept
from appusers.models import User
from appusers.views import register, login_user

sitemaps = {
    'articles': ArticleSitemap,
    'static': StaticViewSitemap
}


def redirect_dashboard(request):
    if request.user.is_authenticated:
        user = User.objects.get(email=request.user)
        group = [g for g in user.groups.all()]
        print(group)
        if len(group) != 0:
            group_name = group[0].name
            if group_name == 'Customer':
                return redirect('/c/orders/')
            if group_name == 'Writer':
                return redirect('/w/orders/')
            if group_name == 'Manager':
                return redirect('/m/orders/')
        else:
            return redirect('/a/')
    else:
        return redirect('/')


admin.site.site_header = 'Панель управления'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', HomePageViews.as_view(), name='home'),
    path('cron/search-deadline/', search_deadline),
    path('cron/check-orders/', check_order),
    path('accounts/login/', login_user, name='login'),
    path('add-comment/', add_testimonial, name='add-comment'),
    path('feedback/', feedback, name='feedback'),
    path('accounts/register/', register, name='register'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('rct/', redirect_dashboard),

    path('ajax/chat-message-accept/', chat_message_accept),
    path('ajax/calculate/', calculate_home),
    path('ajax/order-feedback/', order_feedback),
    path('ajax/add-word/', add_word),
    path('blog/', include('appblog.urls', namespace='appblog')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('c/', include('appdashboard.c', namespace='customer')),
    path('w/', include('appdashboard.w', namespace='writer')),
    path('m/', include('appdashboard.m', namespace='manager')),
    path('a/', include('appdashboard.a', namespace='administrator')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from appblog.views import ListArticles, article, article_edit, article_remove

app_name = 'appblog'
urlpatterns = [
    path('', ListArticles.as_view(), name='main'),
    path('article/<int:pk>/edit/', article_edit, name='article-edit'),
    path('article/<int:pk>/remove/', article_remove, name='article-remove'),
    path('article/<int:pk>/', article, name='article'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appdashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from appdashboard.users import admin
from appdashboard.users.manager import *
from appdashboard import views
from appcourses import views as course
from apporders.views import *
from appusers.views import change_profile

app_name = 'appdashboard'
urlpatterns = [
    path('change-profile/', change_profile, name='change-profile'),
    # Customer
    path('c/course/<int:course_id>/', course.customer_course_detail, name='customer-course-detail'),
    path('c/course/', course.customer_index, name='customer-course-index'),
    # WRITER
    path('w/order/completed-<int:pk>/', writer_order_completed, name='writer-order_completed'),
    path('w/order/detail-<int:pk>/', writer_order_detail, name='writer-order_detail'),
    path('w/order/review-<int:pk>/', writer_order_review, name='writer-order_review'),
    path('w/task/process/<slug:task_slug>/', writer_task_process, name='writer-task-process'),
    path('w/task/<slug:task_slug>/', writer_task_detail, name='writer-task-detail'),
    path('w/tasks/', writer_tasks, name='writer-tasks'),
    # path('feedback/<int:pk>/', feedback_view, name='feedback-view'),
    path('others/comment/<int:pk>/', views.comment_view, name='comment-view'),
    path('others/', views.others, name='others'),
    # ADMIN
    path('writer/<int:pk>/orders/', admin.admin_detail_writer_orders, name='admin-writer-orders'),
    path('writer/<int:pk>/', admin.admin_detail_writer, name='admin-writer'),
    path('customer/<int:pk>/', admin.admin_detail_customer, name='admin-customer'),
    path('manager/<int:pk>/', admin.admin_detail_manager, name='admin-manager'),
    path('users/', admin.admin_users, name='admin-users'),
    path('selects/', admin.admin_selects, name='admin-selects'),
    path('settings/', admin.admin_settings, name='admin-settings'),
    path('billing/', views.DashboardViews.as_view(), name='admin-billing'),
    # Manager
    path('m/writer/<int:pk>/orders/', manager_detail_writer_orders, name='manager-writer-orders'),
    path('m/writer/<int:pk>/', manager_detail_writer, name='manager-writer'),
    path('m/customer/<int:pk>/', manager_detail_customer, name='manager-customer'),
    path('m/order/<int:pk>/', manager_order, name='manager-order'),
    path('m/selects/type-order/<int:pk>/', type_order_remove, name='selects-type_order-remove'),
    path('m/selects/format-order/<int:pk>/', format_order_remove, name='selects-format_order-remove'),
    path('m/selects/price-deadline-order/<int:pk>/', price_deadline_order_remove, name='selects-price_deadline-remove'),
    path('m/selects/', manager_selects, name='manager-selects'),
    path('m/settings/', manager_settings, name='manager-settings'),
    path('m/courses/<int:course_id>/', course.manager_course_detail, name='manager-course-detail'),
    path('m/courses/', course.manager_courses, name='manager-courses'),
    path('m/users/', manager_users, name='manager-users'),
    path('', views.DashboardViews.as_view(), name='dashboard'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/manager/users/tabs/writers/all-writers.html
<table id="allWriters" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
    <tr>
        <th class="th-sm">
            Fullname
        </th>
        <th class="th-sm">
            Email
        </th>
        <th class="th-sm">
            Balance
        </th>
        <th class="th-sm">
            Orders
        </th>
        <th class="th-sm">
            Chat
        </th>
    </tr>
    </thead>
    <tbody>
    {% for writer in writers %}
        <tr>
            <td><a href="{% url 'appdashboard:manager-writer' writer.id %}">{{ writer.get_full_name }}</a></td>
            <td><a href="{% url 'appdashboard:manager-writer' writer.id %}">{{ writer.email }}</a></td>
            <td>{{ writer.balance }}</td>
            <td><a href="{% url 'appdashboard:manager-writer-orders' writer.id %}"><i class="far fa-eye"></i></a></td>
            <td><a href="{% url 'chat' writer.chatuser.id %}"><i class="far fa-comments"></i></a></td>
        </tr>
    {% endfor %}

    </tbody>
    <tfoot>
    <tr>
        <th>
            Fullname
        </th>
        <th>
            Email
        </th>
        <th>
            Balance
        </th>
        <th>
            Orders
        </th>
        <th>
            Chat
        </th>
    </tr>
    </tfoot>
</table>

templates/dashboard/manager/users/tabs/writers/create-writer.html
<form action="{% url 'appdashboard:admin-users' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table">
        {{ new_writer }}
    </table>
    <input type="submit" class="btn bg-btn" name="_create_writer" value="Create">
</form>

templates/dashboard/manager/users/tabs/writers/progress.html
<table id="writerProgress" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
    <tr>
        <th class="th-sm">
            Writer
        </th>
        <th class="th-sm">
            Order
        </th>
        <th class="th-sm">
            Total cost
        </th>
    </tr>
    </thead>
    <tbody>
    {% for order in orders_in_progress %}
        <tr>
            <td>{{ order.writer.get_full_name }}</td>
            <td>{{ order.title }}</td>
            <td>{{ order.total_cost }}</td>
        </tr>
    {% endfor %}

    </tbody>
    <tfoot>
    <tr>
        <th>
            Writer
        </th>
        <th>
            Order
        </th>
        <th>
            Total cost
        </th>
    </tr>
    </tfoot>
</table>