EsseyRoyal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.sitemaps.views import sitemap
from django.shortcuts import redirect
from django.urls import path, include

from appaaa.cron import search_deadline, check_order
from appaaa.sitemaps import ArticleSitemap, StaticViewSitemap
from appaaa.views import HomePageViews, feedback, calculate_home, order_feedback, add_testimonial, add_word
from apporders.ajax import chat_message_accept
from appusers.models import User
from appusers.views import register, login_user

sitemaps = {
    'articles': ArticleSitemap,
    'static': StaticViewSitemap
}


def redirect_dashboard(request):
    if request.user.is_authenticated:
        user = User.objects.get(email=request.user)
        group = [g for g in user.groups.all()]
        print(group)
        if len(group) != 0:
            group_name = group[0].name
            if group_name == 'Customer':
                return redirect('/c/orders/')
            if group_name == 'Writer':
                return redirect('/w/orders/')
            if group_name == 'Manager':
                return redirect('/m/orders/')
        else:
            return redirect('/a/')
    else:
        return redirect('/')


admin.site.site_header = 'Панель управления'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', HomePageViews.as_view(), name='home'),
    path('cron/search-deadline/', search_deadline),
    path('cron/check-orders/', check_order),
    path('accounts/login/', login_user, name='login'),
    path('add-comment/', add_testimonial, name='add-comment'),
    path('feedback/', feedback, name='feedback'),
    path('accounts/register/', register, name='register'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('rct/', redirect_dashboard),

    path('ajax/chat-message-accept/', chat_message_accept),
    path('ajax/calculate/', calculate_home),
    path('ajax/order-feedback/', order_feedback),
    path('ajax/add-word/', add_word),
    path('blog/', include('appblog.urls', namespace='appblog')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('c/', include('appdashboard.c', namespace='customer')),
    path('w/', include('appdashboard.w', namespace='writer')),
    path('m/', include('appdashboard.m', namespace='manager')),
    path('a/', include('appdashboard.a', namespace='administrator')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from appblog.views import ListArticles, article, article_edit, article_remove

app_name = 'appblog'
urlpatterns = [
    path('', ListArticles.as_view(), name='main'),
    path('article/<int:pk>/edit/', article_edit, name='article-edit'),
    path('article/<int:pk>/remove/', article_remove, name='article-remove'),
    path('article/<int:pk>/', article, name='article'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appdashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from appdashboard.users import admin
from appdashboard.users.manager import *
from appdashboard import views
from appcourses import views as course
from apporders.views import *
from appusers.views import change_profile

app_name = 'appdashboard'
urlpatterns = [
    path('change-profile/', change_profile, name='change-profile'),
    # Customer
    path('c/course/<int:course_id>/', course.customer_course_detail, name='customer-course-detail'),
    path('c/course/', course.customer_index, name='customer-course-index'),
    # WRITER
    path('w/order/completed-<int:pk>/', writer_order_completed, name='writer-order_completed'),
    path('w/order/detail-<int:pk>/', writer_order_detail, name='writer-order_detail'),
    path('w/order/review-<int:pk>/', writer_order_review, name='writer-order_review'),
    path('w/task/process/<slug:task_slug>/', writer_task_process, name='writer-task-process'),
    path('w/task/<slug:task_slug>/', writer_task_detail, name='writer-task-detail'),
    path('w/tasks/', writer_tasks, name='writer-tasks'),
    # path('feedback/<int:pk>/', feedback_view, name='feedback-view'),
    path('others/comment/<int:pk>/', views.comment_view, name='comment-view'),
    path('others/', views.others, name='others'),
    # ADMIN
    path('writer/<int:pk>/orders/', admin.admin_detail_writer_orders, name='admin-writer-orders'),
    path('writer/<int:pk>/', admin.admin_detail_writer, name='admin-writer'),
    path('customer/<int:pk>/', admin.admin_detail_customer, name='admin-customer'),
    path('manager/<int:pk>/', admin.admin_detail_manager, name='admin-manager'),
    path('users/', admin.admin_users, name='admin-users'),
    path('selects/', admin.admin_selects, name='admin-selects'),
    path('settings/', admin.admin_settings, name='admin-settings'),
    path('billing/', views.DashboardViews.as_view(), name='admin-billing'),
    # Manager
    path('m/writer/<int:pk>/orders/', manager_detail_writer_orders, name='manager-writer-orders'),
    path('m/writer/<int:pk>/', manager_detail_writer, name='manager-writer'),
    path('m/customer/<int:pk>/', manager_detail_customer, name='manager-customer'),
    path('m/order/<int:pk>/', manager_order, name='manager-order'),
    path('m/selects/type-order/<int:pk>/', type_order_remove, name='selects-type_order-remove'),
    path('m/selects/format-order/<int:pk>/', format_order_remove, name='selects-format_order-remove'),
    path('m/selects/price-deadline-order/<int:pk>/', price_deadline_order_remove, name='selects-price_deadline-remove'),
    path('m/selects/', manager_selects, name='manager-selects'),
    path('m/settings/', manager_settings, name='manager-settings'),
    path('m/courses/<int:course_id>/', course.manager_course_detail, name='manager-course-detail'),
    path('m/courses/', course.manager_courses, name='manager-courses'),
    path('m/users/', manager_users, name='manager-users'),
    path('', views.DashboardViews.as_view(), name='dashboard'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apporders/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from apporders.views import *

app_name = 'apporders'
urlpatterns = [
    path('progress/<int:pk>/', customer_order_in_progress, name='customer-progress_order'),
    path('completed/<int:pk>/', customer_order_in_completed, name='customer-completed_order'),
    path('published/<int:pk>/', order_published, name='published_order'),
    path('view/<int:pk>/', ViewOrderViews.as_view(), name='view_order'),
    path('update/<int:pk>/', UpdateOrderViews.as_view(), name='update_order'),
    path('new', add_order_views, name='add_order'),
    path('remove', remove_order, name='remove'),
    path('completed/<int:pk>/', completed_order, name='completed'),
    path('completed/feedback/<int:pk>/', completed_order_feedback, name='completed-feedback'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/customer/tabs/new-order.html
<form action="{% url 'apporders:add_order' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <table class="table">
        {% for field in new_order %}
            <tr>
                <td width="120">{{ field.label }}</td>
                <td>{{ field }}</td>
            </tr>
            {% if field.errors %}
                <tr>
                    <td></td>
                    <td>{{ field.errors }}</td>
                </tr>
            {% endif %}
        {% endfor %}
        <tr>
            <td><label for="id_attached-files">Attached files</label></td>
            <td>
                <input type="file" name="attached-files" id="id_attached-files" multiple>
                <small>.xls .docx .pdf .xlsx</small>
            </td>
        </tr>
        <tr>
            <td>Per page:</td>
            <td id="per_page"></td>
        </tr>
        <tr>
            <td>Total cost:</td>
            <td id="total_cost"></td>
        </tr>
    </table>
    <button type="submit" class="btn bg-btn">Send</button>
</form>

templates/dashboard/customer/tabs/orders.html
<div class="modal fade" id="modalConfirmDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-sm modal-notify modal-danger" role="document">
    <!--Content-->
    <div class="modal-content text-center">
      <!--Header-->
      <div class="modal-header d-flex justify-content-center">
        <p class="heading">Are you sure?</p>
      </div>

      <!--Body-->
      <div class="modal-body">

        <i class="fas fa-times fa-4x animated rotateIn"></i>

      </div>

      <!--Footer-->
      <div class="modal-footer flex-center">
          <form action="{% url 'apporders:remove' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn  btn-outline-danger" id="id_remove" name="_remove" value="">Yes</button>
          </form>
        <a type="button" class="btn  btn-danger waves-effect" data-dismiss="modal">No</a>
      </div>
    </div>
    <!--/.Content-->
  </div>
</div>


<div class="tab-pane fade active show" id="panel83" role="tabpanel">
    <div class="table-responsive">
        <table class="table">
            <thead class="th-center">
            <tr>
                <th class="text-center">Status</th>
                <th align="middle">Title</th>
                <th>Type of order</th>
                <th>Per page</th>
                <th>Pages</th>
                <th class="text-center">Total cost</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody class="td-center">
            {% for order in orders %}
                <tr>
                    <td class="text-center">
                        {% if order.status == 0 %}
                            <i class="fas fa-search" title="ORDER IN REVIEW"></i>
                        {% elif order.status == 1 %}
                            <i class="fas fa-spinner fa-pulse" title="ORDER IN PROGRESS"></i>
                        {% elif order.status == 2 %}
                            <i class="fas fa-check" title="COMPLETED"></i>
                        {% elif order.status == 3 %}
                            <i class="fas fa-cash-register"></i>
                        {% endif %}
                    </td>
                    <td>{{ order.title }}</td>
                    <td>{{ order.type_order }}</td>
                    <td>${{ order.per_page }}</td>
                    <td>{{ order.number_page }}</td>
                    <td class="text-center">${{ order.total_cost }}</td>
                    <td class="text-center">
                        {% if order.status == 0 %}
                            <a href="{% url 'apporders:view_order' order.id %}" class="blue-text" data-toggle="tooltip"
                               data-placement="top" title=""
                               data-original-title="See results"><i class="far fa-eye"></i></a>
                            <a href="{% url 'apporders:update_order' order.id %}" class="teal-text" data-toggle="tooltip"
                               data-placement="top" title=""
                               data-original-title="Edit"><i
                                    class="fas fa-pencil-alt"></i></a>

                            <a class="red-text customer_remove_order" data-order-id="{{ order.id }}"
                                   data-toggle="modal"
                                   data-target="#modalConfirmDelete"
                                   data-original-title="Remove">
                                <i class="fas fa-times"></i>
                            </a>
                        {% elif order.status == 1 %}
                            <a href="{% url 'apporders:customer-progress_order' order.id %}" class="blue-text"
                               data-toggle="tooltip"
                               data-placement="top" title=""
                               data-original-title="See results"><i class="far fa-eye"></i></a>
                        {% elif order.status == 2 %}
                            <a href="{% url 'apporders:customer-completed_order' order.id %}" class="blue-text"
                               data-toggle="tooltip"
                               data-placement="top" title=""
                               data-original-title="See results"><i class="far fa-eye"></i></a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

templates/dashboard/customer/tabs/settings.html
<form action="{% url 'appdashboard:change-profile' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table customer-table-td">
        {{ user_form.as_table }}
    </table>
    <button class="btn bg-btn">Save</button>
</form>